### ISSUE TITLE
Can you add read me?

### ISSUE THREAD

**Issue by Shadow2121** [RathodVipul234/Dream11Prediction#1]
hi @RathodVipul234
Can you add read me to this repository or can you explain what the project is?

**Comment by RathodVipul234** [comment]
Nothing bro just i want create smallwebsite which show about predictikn of
cricket match.

It just small part and i am uoload soon in puthon anywhere for learning
perspective.

**Comment by Shadow2121** [comment]
Is it about predicting the team which will do good in match? Like some ML to predict today's team.

**Comment by RathodVipul234** [comment]
there is nothing with ML  just im uploading my predicted dream 11 team and
its statistics and record  from admin site and its show in usersite.

**Comment by Shadow2121** [comment]
OOh ok I see thank you. @RathodVipul234
